apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    name:  example
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb-service
subsets:
  - addresses:
      - ip: 10.62.176.1
    ports:
      - port: 27017